apiVersion: v1
kind: Pod
metadata:
  name: sailorpod
spec:
  containers:
    - name: sailor
      image: vinodck1991/sailor:1.0
      
      ports:
        - name: tomcatport
          containerPort: 8080
          protocol: TCP
